### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by anes66** [Bluethefurry/EasyAdmin-MySQL#1]
Hello i have a 4 servers (FiveM) connected to 1 database and when i ban peopel from server 1 they still can after that join server 2,3,4 but in console it says retrieved banlist from all server do you know where the problem maybe is?

**Comment by Blumlaut** [comment]
make sure they are retrieving the banlist after you ban them, they still have a short timeframe when they can join after they get banned, after that it should work though.

**Comment by anes66** [comment]
> make sure they are retrieving the banlist after you ban them, they still have a short timeframe when they can join after they get banned, after that it should work though.

thx yeah after some time they cant join on server anymore and ofc dude thx for the very nice stuff and usefull staff keep you work
