### ISSUE TITLE
Missing end for For loop at line.89

### ISSUE THREAD

**Issue by ithmz** [Bluethefurry/EasyAdmin-MySQL#2]
https://github.com/Bluethefurry/EasyAdmin-MySQL/blob/ba09488c699b05ce0c59f3802ca882050fcb287b/server.lua#L94

**Comment by Blumlaut** [comment]
Sorry 'bout that! Fixed in https://github.com/Bluethefurry/EasyAdmin-MySQL/commit/931c99d393d89b3912b26a64390b6f1ed47acdc1
